<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?=$this->headTitle("zIndex管理系统")?>
	<link href="/resource/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/admin/">zIndex管理系统</a>
  </div>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<div class="bs-docs-sidebar">
				
				<div class="accordion" id="accordion2">
				  <div class="accordion-group">
					<div class="accordion-heading">
					  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
						公司管理
					  </a>
					</div>
					<div id="collapseOne" class="accordion-body collapse in">
						<div class="accordion-inner">
					  <ul class="nav nav-pills nav-stacked">
						<li><a href="/admin/company/create">创建公司</a></a></li>
						<li><a href="/admin/company">公司管理</a></a></li>
						
						<li><a href="/admin/contactuser/create">创建联系人</a></a></li>
						<li><a href="/admin/contactuser">联系人管理</a></a></li>
						
						<li><a href="/admin/company-scale">管理公司规模项</a></a></li>
						<li><a href="/admin/company-nature">管理公司性质项</a></a></li>
						<li><a href="/admin/company-industry">管理公司行业项</a></a></li>
					</ul>
					</div>
					</div>
				  </div>
				  <div class="accordion-group">
					<div class="accordion-heading">
					  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
						工作管理
					  </a>
					</div>
					<div id="collapseTwo" class="accordion-body collapse in">
						<div class="accordion-inner">
						  <ul class="nav nav-pills nav-stacked">
							<li><a href="/admin/job/create">创建工作</a></a></li>
							<li><a href="/admin/job">工作管理</a></a></li>
							
							<li><a href="/admin/job-category/create">创建工作分类</a></a></li>
							<li><a href="/admin/job-category">工作分类管理</a></a></li>
						</ul>
						</div>
					</div>
				  </div>
				  
				</div>
				
			</div>
		</div>

		<div class="span10">
			<?=$this->content?>
		</div>
	</div>
</div>

<script src="/js/jquery-1.8.2.min.js"></script>
<script src="/resource/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>