			<h1 class="page-header">联系人管理</h1>
			
			<section>
				<div class="navbar btn-toolbar">
					<div class="navbar-inner">
						<a href="/admin/contact-user/create" class="btn btn-success">创建新联系人</a>
						
						<div class="btn-group" >
							<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
								批量操作
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a>删除</a></li>
							</ul>
						</div>
						
					</div>
				</div>
				
				<table class="table table-striped">
					<tr><th width="30"><input type="checkbox" /></th><th width="60">#</th><th>联系人</th><th>公司</th><th width="150">创建时间</th><th width="150">操作</th></tr>
					<?foreach($users as $key=>$value){?>
					<tr><td><input type="checkbox" /></td>
						<td><?=$value['uid']?></td>
						<td><?=$value['username']?></td>
						<td><?=$value['company_name']?></td>
						<td><?=$value['created_time']?></td>
						<td><div class="btn-group">
							<a href="/admin/contact-user/edit?id=<?=$value['uid']?>" class="btn btn-primary btn-small">修改</a>
							<a href="/admin/contact-user/delete?id=<?=$value['uid']?>" class="btn btn-danger btn-small">删除</a>
						</div></td></tr>
					<?}?>
				</table>
				
				<div class="pagination">
					<?=$pager?>
				</div>
			</section>