<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>青岛web达人联盟招聘汇总</title>
<link href="/resource/css/style.css" rel="stylesheet" />

</head>

<body>
<header>青岛Web达人联盟招聘汇总</header>
<div class="words">青岛Web达人联盟是青岛所有it设计、用户体验、软件、游戏及移动互联和动漫达人联盟, 欢迎各界朋友的加盟。<br /><span class="h6">QQ群：202585388</span>
</div>
<section class="content">
<?php echo $this->content; ?>
</section>
</body>
</html>