			<h1 class="page-header">编辑公司行业</h1>
			<?if(isset($messages)){?>
			<?=$this->messager($messages)?>
			<?}?>
			<section>
				<form method="post" class="form-horizontal">
					<legend>公司行业信息</legend>
					
					<div class="control-group">
						<label class="control-label" for="username">名称</label>
						<div class="controls">
							<input type="text" name="name" id="name" placeholder="名称" value="<?=$industry->name?>" />
						</div>
					</div>
					
					<div class="control-group">
						<div class="controls">
							<input type="submit" name="submit" value="提交" class="btn btn-primary" />
						</div>
					</div>
				</form>
			</section>