<?foreach($companies as $company){?>
<article class="jobs">
	<div class="h1"><?=$company['name']?></div>
	<ul>
		<li><h3>公司简介</h3><div><?=$company['description']?></div></li>
		<li><h3>公司地址</h3><div><?=$company['address']?></div></li>
	
	
		<li>
		<h3>工作</h3>
		<?if(isset($tjobs[$company['company_id']])){foreach( $tjobs[$company['company_id']] as $tj){?>
		
		<dl>
			<dt><?=$tj['title']?></dt>
			<dd><?=$tj['pay']?></dd>
			<dd><?=$tj['treatment']?></dd>
			<dd><?=$tj['duty']?></dd>
			<dd><?=$tj['requirement']?></dd>
		</dl>
		<?}}else{?>
		暂无工作信息
		<?}?>
		</li>
	</ul>
</article>
<?}?>
