	<style>
	.form-signin{max-width: 400px;margin:0 auto;}
	</style>
	
	<form class="form-signin" method="post">
		<?if(isset($messages)){?>
		<?=$this->messager($messages)?>
		<?}?>
		<h2 class="form-signin-heading">用户注册</h2>
		<input type="text" class="input-block-level" placeholder="Email" name="email">
		<input type="text" class="input-block-level" placeholder="用户名" name="username">
		<input type="password" class="input-block-level" placeholder="密码" name="password">
		<input type="password" class="input-block-level" placeholder="重复密码" name="repassword">
		<button class="btn btn-large btn-primary" type="submit">
			注册
		</button>
	</form>