			<?
			$this->headTitle()->prepend("欢迎登陆");
			$this->headTitle()->setSeparator('-');
			?>
			<div class="hero-unit">
				<h1>欢迎使用</h1>
				<p>欢迎使用zIndex工作管理系统</p>
				<p>
				<div class="btn-group">
				  <a class="btn btn-primary">管理公司</a>
				  <a class="btn btn-info">管理工作</a>
				  <a class="btn btn-success">管理联系人</a>
				  <a class="btn btn-warning">管理工作分类</a>
				</div>
				</p>
			</div>