<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?=$this->headTitle("zIndex管理系统")?>
	<link href="/resource/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/admin/">zIndex管理系统</a>
  </div>
</div>

<div class="container-fluid">
	<div class="row-fluid">
			<?=$this->content?>
	</div>
</div>

<script src="/js/jquery-1.8.2.min.js"></script>
<script src="/resource/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>