		<?
		$this->headTitle()->prepend("新增工作职位");
		$this->headTitle()->setSeparator('-');
		?>
		<h1 class="page-header">新增工作职位</h1>
		<?if(isset($messages)){?>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">×</button>
			<?=$messages[0]?>
		</div>
		<?}?>
		<section>
			<form method="post" class="form-horizontal">
				<legend>工作职位信息</legend>
				<div class="control-group">
					<label class="control-label" for="title">工作名称</label>
					<div class="controls">
						<input type="text" name="title" id="title" placeholder="工作名称" />
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="username">所属公司</label>
					<div class="controls">
						<?=$this->company_selector($companies)?>
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="username">工作分类</label>
					<div class="controls">
						<?=$this->job_category_selector($jobCategories)?>
					</div>
				</div>
				
				
				<div class="control-group">
					<label class="control-label" for="address">工作地址</label>
					<div class="controls">
						<input type="text" name="address" id="address" placeholder="工作地址" />
					</div>
				</div>
				
				
				
				<div class="control-group">
					<label class="control-label" for="pay">薪资</label>
					<div class="controls">
						<input type="text" name="pay" id="pay" placeholder="薪资" />
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="treatment">待遇</label>
					<div class="controls">
						<textarea name="treatment" id="treatment" placeholder="待遇" class="span6" ></textarea>
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="duty">职责</label>
					<div class="controls">
						<textarea name="duty" id="duty" placeholder="职责" class="span6" ></textarea>
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="requirement">要求</label>
					<div class="controls">
						<textarea name="requirement" id="requirement" placeholder="要求" class="span6" ></textarea>
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="person_number">需要人数</label>
					<div class="controls">
						<input type="text" name="person_number" id="person_number" placeholder="需要人数" />
					</div>
				</div>
				
				
				<div class="control-group">
					<div class="controls">
						<input type="submit" name="submit" value="提交" class="btn btn-primary" />
					</div>
				</div>
			</form>
		</section>
