			
			
			<h1 class="page-header">公司性质管理</h1>
			
			<section>
				<div class="navbar btn-toolbar">
					<div class="navbar-inner">
						<a href="/admin/company-nature/create" class="btn btn-success">新增公司性质</a>
						
						<div class="btn-group" >
							<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
								批量操作
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a>删除</a></li>
							</ul>
						</div>
						
					</div>
				</div>
				
				<table class="table table-striped">
					<tr><th width="30"><input type="checkbox" /></th><th width="60">#</th><th>名称</th><th width="150">操作</th></tr>
					<?foreach($natures as $key=>$value){?>
					<tr>
						<td><input type="checkbox" /></td>
						<td><?=$value['id']?></td>
						<td><?=$value['name']?></td>
						<td><div class="btn-group">
							<a href="/admin/company-nature/edit?id=<?=$value['id']?>" class="btn btn-primary btn-small">修改</a>
							<a href="/admin/company-nature/delete?id=<?=$value['id']?>" class="btn btn-danger btn-small delete">删除</a>
						</div></td></tr>
					<?}?>
				</table>
				
				<div class="pagination">
					<?=$pager?>
				</div>
			</section>
			
			<script src="/resource/js/confirm-del.js"></script>